/*
 *  File: header.c
 *
 *  FM64 Oscillator unit header
 *
 *
 *  2024-2025 (c) Oleg Burdaev
 *  mailto: dukesrg@gmail.com
 */

#include "logue_wrap.h"

#define STR(x) #x
#define IDX(x) STR(x)

const __unit_header UNIT_HEADER_TYPE unit_header = {
#ifdef UNIT_TARGET_PLATFORM_NTS3_KAOSS
    .common = {
#endif
    .header_size = sizeof(UNIT_HEADER_TYPE),
    .target = UNIT_HEADER_TARGET_VALUE,
    .api = UNIT_API_VERSION,
    .dev_id = 0x44756B65U,
#if FM == 64
    .unit_id = 0x34364D46U,
#elif FM == 65
    .unit_id = 0x35364D46U,
#elif FM == 66
    .unit_id = 0x35364D46U,
#elif FM == 67
    .unit_id = 0x37364D46U,
#elif FM == 68
    .unit_id = 0x38364D46U,
#elif FM == 69
    .unit_id = 0x39364D46U,
#elif FM == 48
    .unit_id = 0x38344D46U,
#endif
    .version = 0x0003000EU,
    .name = "FM"IDX(FM),
#if defined(UNIT_TARGET_PLATFORM_DRUMLOGUE) || defined(UNIT_TARGET_PLATFORM_MICROKORG2)
    .num_presets = 0,
#endif
    .num_params = PARAM_COUNT,
    .params = {
#if defined(UNIT_TARGET_PLATFORM_NTS1_MKII)
        {0, 1023, 0, 1023, k_unit_param_type_none, 3, k_unit_param_frac_mode_fixed, 0, {"Velocity"}},
        {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB scale"}},
#ifdef KIT_MODE
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Voice Shift1"}},
        {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"Split Point1"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose 2"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Voice Shift2"}},
        {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"Split Point2"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose 3"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Voice Shift3"}},
#else
        {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice"}},
        {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal All"}},
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs All"}},
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Car"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Alg offset"}},
#ifdef WFGEN
        {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Car"}},
#else
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Mod"}},
#endif
#ifdef WAVE_PINCH
        {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Car"}},
        {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Mod"}},
#else
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Car"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose"}},
#endif
#endif
#elif defined(UNIT_TARGET_PLATFORM_NTS3_KAOSS)
        {0, 1023, 0, 1023, k_unit_param_type_none, 3, k_unit_param_frac_mode_fixed, 0, {"Velocity"}},
        {-16384, 16383, 0, 0, k_unit_param_type_none, 8, k_unit_param_frac_mode_fixed, 0, {"Pitch"}},
        {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice"}},
        {0, 50, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Arp"}},
        {0, 36, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Scale"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose"}},
        {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {""}},
        {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {""}},
#elif defined(UNIT_TARGET_PLATFORM_DRUMLOGUE)

#elif defined(UNIT_TARGET_PLATFORM_MICROKORG2)
        {0, 1023, 0, 1023, k_unit_param_type_none, 3, k_unit_param_frac_mode_fixed, 0, {"Velocity"}},
        {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB scale"}},
#ifdef KIT_MODE
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp."}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"VceShft1"}},
        {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"SplitPnt1"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp.2"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"VceShft2"}},
        {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"SplitPnt2"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp.3"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"VceShft3"}},
#else
        {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice"}},
        {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScalA"}},
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffsA"}},
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffsC"}},
        {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Alg offs"}},
#ifdef WFGEN
        {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"WavefrmC"}},
#else
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffsM"}},
#endif
#ifdef WAVE_PINCH
        {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WFPinchC"}},
        {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WFPinchM"}},
#else
        {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffsC"}},
        {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp."}},
#endif
#endif
#endif
    }
#if defined(UNIT_TARGET_PLATFORM_NTS3_KAOSS)
    },
    .default_mappings = {
        {k_genericfx_param_assign_y, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 1023, 1023},
        {k_genericfx_param_assign_x, k_genericfx_curve_linear, k_genericfx_curve_unipolar, -3072, 3071, 0},
        {k_genericfx_param_assign_depth, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, BANK_COUNT * 32 - 1, 0},
        {k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 50, 0},
        {k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 36, 0},
        {k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, -128, 127, 0},
        {k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 0, 0},
        {k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 0, 0},
    }
#endif
};

#ifdef WAVE_PINCH
#define CUSTOM_PARAM_COUNT 153
#elif defined (WFBITS)
#define CUSTOM_PARAM_COUNT 144
#elif defined (WFGEN)
#define CUSTOM_PARAM_COUNT 156
#else
#ifdef UNIT_TARGET_PLATFORM_NTS3_KAOSS
#define CUSTOM_PARAM_COUNT 158
#else
#define CUSTOM_PARAM_COUNT 133
#endif
#endif

#include "custom_param.h"

CUSTOM_PARAMS(
#ifdef UNIT_TARGET_PLATFORM_MICROKORG2
    {0, 1023, 0, 1023, k_unit_param_type_none, 3, k_unit_param_frac_mode_fixed, 0, {"Velocity"}},
    {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice"}},
    {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice 2"}},
    {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice 3"}},
    {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"SplitPnt1"}},
    {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"SplitPnt2"}},
    {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp."}},
    {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp.2"}},
    {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transp.3"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"VceShft1"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"VceShft2"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"VceShft3"}},
//    {-99, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Shape Assign"}},
//    {-99, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Alt Assign"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#if FEEDBACK_COUNT == 2
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"FB offs"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"FB2 offs"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB scal"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB2 scal"}},
#ifdef OP6
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB2 route"}},
#else
    {0, 16, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
    {0, 16, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB2route"}},
#endif
#else
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"FB offs"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB scal"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#ifdef OP6
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
#else
    {0, 16, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
#endif
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#endif
    {0, 85, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Alg slct"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Alg offs"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffsA"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffsC"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffsM"}},
#ifdef OP6
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs6"}},
#else
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"LvlOffs4"}},
#endif
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScalA"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScalC"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScalM"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScal1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScal2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScal3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScal4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScal5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"LvlScal6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffsA"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffsC"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffsM"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffs4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffs5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLSOffs6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScalA"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScalC"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScalM"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScal1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScal2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScal3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScal4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScal5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLSScal6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffsA"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffsC"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffsM"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffs4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffs5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVSOffs6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScalA"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScalC"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScalM"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScal1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScal2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScal3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScal4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScal5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVSScal6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffsA"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffsC"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffsM"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffs4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffs5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"RatOffs6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScalA"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScalC"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScalM"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScal1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScal2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScal3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScal4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScal5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"RatScal6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffsA"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffsC"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffsM"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffs4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffs5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRSOffs6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScalA"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScalC"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScalM"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScal1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScal2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScal3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScal4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScal5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRSScal6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffsA"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffsC"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffsM"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffs1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffs2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffs3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffs4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffs5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"DetOffs6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScalA"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScalC"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScalM"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScal1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScal2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScal3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScal4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScal5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"DetScal6"}},
#ifdef WFGEN
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"WavefrmA"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"WavefrmC"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"WavefrmM"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Wavefrm1"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Wavefrm2"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Wavefrm3"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Wavefrm4"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Wavefrm5"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Wavefrm6"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#endif
//ToDo: WFBITS is not defined here
#ifdef WFBITS
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform C+M"}},
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform 1+2"}},
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform 3+4"}},
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform 5+6"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform All"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Car"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Mod"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op1"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op2"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op3"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op4"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op5"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op6"}},
#elif defined(WAVE_PINCH)
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch All"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Car"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Mod"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op1"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op2"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op3"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op4"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op5"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op6"}},
#endif
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
//end microkorg2
#else
    {0, 1023, 0, 1023, k_unit_param_type_none, 3, k_unit_param_frac_mode_fixed, 0, {"Velocity"}},
    {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice"}},
    {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice 2"}},
    {0, BANK_COUNT * 32 - 1, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Voice 3"}},
    {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"Split Point 1"}},
    {0, 127, 0, 0, k_unit_param_type_midi_note, 0, k_unit_param_frac_mode_fixed, 0, {"Split Point 2"}},
    {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose"}},
    {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose 2"}},
    {-128, 127, 0, 0, k_unit_param_type_semi, 0, k_unit_param_frac_mode_fixed, 0, {"Transpose 3"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Voice Shift 1"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Voice Shift 2"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Voice Shift 3"}},
//    {-99, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Shape Assign"}},
//    {-99, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Alt Assign"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#if FEEDBACK_COUNT == 2
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"FB offset"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"FB2 offset"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB scale"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB2 scale"}},
#ifdef OP6
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB 2 route"}},
#else
    {0, 16, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
    {0, 16, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB 2 route"}},
#endif
#else
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"FB offset"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"FB scale"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#ifdef OP6
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
#else
    {0, 16, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"FB route"}},
#endif
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#endif
    {0, 85, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Alg select"}},
    {-128, 127, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Alg offset"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs All"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Car"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Mod"}},
#ifdef OP6
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op6"}},
#else
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Lvl offs Op4"}},
#endif
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal All"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Car"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Mod"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Op1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Op2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Op3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Op4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Op5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Lvl scal Op6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs All"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Car"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Mod"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Op4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Op5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"KLS offs Op6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal All"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Car"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Mod"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Op1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Op2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Op3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Op4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Op5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KLS scal Op6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs All"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Car"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Mod"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Op4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Op5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KVS offs Op6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal All"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Car"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Mod"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Op1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Op2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Op3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Op4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Op5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KVS scal Op6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs All"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Car"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Mod"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Op4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Op5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Rat offs Op6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal All"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Car"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Mod"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Op1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Op2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Op3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Op4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Op5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Rat scal Op6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs All"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Car"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Mod"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Op4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Op5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 6, k_unit_param_frac_mode_fixed, 0, {"KRS offs Op6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal All"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Car"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Mod"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Op1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Op2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Op3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Op4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Op5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"KRS scal Op6"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs All"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Car"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Mod"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Op1"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Op2"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Op3"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Op4"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Op5"}},
    {-512, 511, 0, 0, k_unit_param_type_none, 2, k_unit_param_frac_mode_fixed, 0, {"Det offs Op6"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal All"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Car"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Mod"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Op1"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Op2"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Op3"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Op4"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Op5"}},
    {0, 1023, 512, 512, k_unit_param_type_none, 9, k_unit_param_frac_mode_fixed, 0, {"Det scal Op6"}},
#ifdef WFGEN
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform All"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Car"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Mod"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op1"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op2"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op3"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op4"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op5"}},
    {0, 132, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op6"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#if UNIT_INPUT_CHANNELS == 0
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#else
    {0, 14, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Input route"}},
#endif
#endif
//ToDo: WFBITS is not defined here
#ifdef WFBITS
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform C+M"}},
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform 1+2"}},
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform 3+4"}},
    {-77, 77, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform 5+6"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform All"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Car"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Mod"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op1"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op2"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op3"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op4"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op5"}},
    {-7, 7, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Waveform Op6"}},
#elif defined(WAVE_PINCH)
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch All"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Car"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Mod"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op1"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op2"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op3"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op4"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op5"}},
    {0, 99, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"WF pinch Op6"}},
#endif
#if defined(UNIT_TARGET_PLATFORM_NTS3_KAOSS)
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#if UNIT_INPUT_CHANNELS == 0
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#else
    {0, 14, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Input route"}},
#endif
    {0, 50, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"Arp"}},
    {0, 36, 0, 0, k_unit_param_type_strings, 0, k_unit_param_frac_mode_fixed, 0, {"Scale"}},
    {-16384, 16383, 0, 0, k_unit_param_type_none, 8, k_unit_param_frac_mode_fixed, 0, {"Pitch"}},
#else
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
    {0, 0, 0, 0, k_unit_param_type_none, 0, k_unit_param_frac_mode_fixed, 0, {"-"}},
#endif
#endif
);
